#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=sonar-portal \
-v "$(pwd)":/app \
-v "$(pwd)"/../configuration:/app/portal-app/src/configuration \
-p 8080:3000 \
louisross/portal:1.0 \
/bin/bash
