FROM node:lts-alpine

LABEL version="1.0"
LABEL description="React-based web page for managing Sonar controller"
LABEL maintainer="Louis Ross <louis.ross@gail.com>"

#COPY ["./package.json", "./package-lock.json", "/app/"]
#RUN ["npm", "insall"]

COPY . .

EXPOSE 3000

#CMD ["npm", "start"]
