#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=sonar-backend \
--device /dev/ttyUSB0 \
-v "$(pwd)":/usr/src/app \
-v "$(pwd)/../configuration/:/configuration" \
-v "/mnt/data/:/sonar" \
-p 5000:5000 \
louisross/sonar-backend:1.0 \
bash
