services:
  sonar-systemmonitor:
    container_name: sonar-systemmonitor
    build: ./
    image: "louisross/sonar-systemmonitor:1.0"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    tty: false
    volumes:
      - "./:/usr/src/monitor"
      - "../configuration/:/configuration"
      - "/mnt/m2/sonar/:/sonar"
