#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=sonar-deploy \
--device /dev/ttyUSB0 \
-v "$(pwd)":/usr/src/app \
-v "$(pwd)/../configuration/:/configuration" \
-v "/mnt/m2/sonar/:/sonar" \
louisross/sonar-deploy:1.0 \
bash
