services:
  sonar-backend:
    container_name: sonar-backend
    restart: unless-stopped
    build: ./backend/
    image: "louisross/sonar-backend:1.1"
    tty: true
    command: 'npm start'
    ports:
      - 5000:5000
    volumes:
      - "./backend:/usr/src/app"
      - "./configuration/:/configuration"
      - "/mnt/sonar/:/sonar"
  sonar-portal:
    container_name: sonar-portal
    restart: unless-stopped
    build: "./portal"
    image: "louisross/portal:1.1"
    tty: true
    command: 'npm start'
    ports:
      - 8080:3000
    volumes:
      - "./portal/:/app"
      - "./configuration/:/app/portal-app/src/configuration"
      - "/mnt/sonar/:/app/portal-app/public/sonar"
    depends_on:
      - sonar-backend
  sonar-deploy:
    container_name: sonar-deploy
    restart: unless-stopped
    build: "./deploy"
    image: "louisross/sonar-deploy:1.1"
    devices:
      - "/dev/SonarSerial:/dev/ttyUSB0"
    tty: true
    command: 'python3 deploy.py'
    volumes:
      - "./deploy:/usr/src/app"
      - "./configuration/:/configuration"
      - "/mnt/sonar/:/sonar"
    depends_on:
      - sonar-backend

