services:
  sonar-backend:
    container_name: sonar-backend
    build: ./backend/
    image: "louisross/sonar-backend:1.1"
    tty: true
    command: 'npm start'
    ports:
      - 5000:5000
    volumes:
      - "./backend:/usr/src/app"
      - "./configuration/:/configuration"
      - "/sonar/:/sonar"
  sonar-portal:
    container_name: sonar-portal
    build: "./portal"
    image: "louisross/portal:1.1"
    tty: true
    command: 'npm start'
    ports:
      - 8080:3000
    volumes:
      - "./portal/:/app"
      - "./configuration/:/app/portal-app/src/configuration"
      - "/sonar/:/app/portal-app/public/sonar"
    depends_on:
      - sonar-backend
  sonar-deploy:
    container_name: sonar-deploy
    build: "./deploy"
    image: "louisross/sonar-deploy:1.1"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    tty: true
    command: 'python3 deploy.py'
    volumes:
      - "./deploy:/usr/src/app"
      - "./configuration/:/configuration"
      - "/sonar/:/sonar"
    depends_on:
      - sonar-backend
  sonar-systemmonitor:
    container_name: sonar-systemmonitor
    build: "./systemmonitor"
    image: "louisross/sonar-systemmonitor:1.0"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    tty: true
    command: 'python3 ./monitor.py'
    volumes:
      - "./systemmonitor:/usr/src/monitor"
      - "../configuration/:/configuration"
      - "/sonar/:/sonar"
